# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: 10.7.251.133:5000/almerico/activiti-cloud-acceptance-tests
  tag: 7.0.19
  pullPolicy: IfNotPresent
  extraEnv: |
    - name: SSO_HOST_ARG
      value: "activiti-keycloak.jx-staging.35.187.184.216.nip.io"
    - name: GATEWAY_HOST
      value: "activiti-cloud-gateway.jx-staging.35.187.184.216.nip.io"
    - name: REALM
      value: "activiti"
    
service:
  name: activiti-cloud-acceptance-tests
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 400m
    memory: 512Mi
probePath: /actuator/health
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10
